
[build]
base = "netlify"
publish = "www"
command = ""

[functions]
directory = "functions"
node_bundler = "esbuild"

[dev]
framework = "#static"
publish = "www"
port = 5000
functionsPort = 5001
autoLaunch = false

[context.dev.environment]
API_ENV = "dev"

[[redirects]]
force = true
from = "/api/*"
to = "/.netlify/functions/:splat"

[[redirects]]
force = true
status = 308
from = "/*"
to = "https://fabiankachlock.dev/"
